WebApplication_Kaido15/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication_Kaido15.Models
{
    public class Student
    {
        public int id { get; set; }

        [Required]
        public string name { get; set; }

        public string address { get; set; }

        [Required]
        public int age { get; set; }

        [Required]
        public string standard { get; set; }

        [Required]
        [RegularExpression(@"^\d+\.\d{0,2}$", ErrorMessage = "Invalid should be like 79.76")]
        public decimal percent { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime addedOn { get; set; }

        [Required]
        public bool status { get; set; }
    }
}

WebApplication_Kaido15/Controllers/CrudOperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Core.Objects;
using WebApplication_Kaido15.Class;

namespace WebApplication_Kaido15.Controllers
{
    public class CrudOperationsController : Controller
    {

        [HttpPost]
        public ActionResult Index(Models.Student student, int? id)
        {
            if (ModelState.IsValid)
            {
                using (var context = new Entities())
                {
                    ObjectParameter result = new ObjectParameter("result", typeof(String));
                    ObjectParameter createdId = new ObjectParameter("createdId", typeof(String));
                    if (id == null)
                        context.sp_InsertStudent(student.name, student.address, student.age, student.standard, student.percent, student.status, result, createdId);
                    else
                        context.sp_UpdateStudent(id, student.name, student.address, student.age, student.standard, student.percent, student.status, result);

                    TempData["Result"] = createdId.Value == null ? result.Value : result.Value + " New Student Id is " + createdId.Value;
                }
            }
            ViewBag.Operation = id == null ? "Add Student" : "Update Student";
            BindStudent(0);
            return View();
        }

        public ActionResult Index(int? id, int? page)
        {
            BindStudent(Convert.ToInt32(page));
            Models.Student mStudent = new Models.Student();
            if (id != null)
            {
                using (var context = new Entities())
                {
                    var result = context.sp_GetStudentById(id);
                    var targetList = result.Select(x => new Models.Student() { id = x.Id, name = x.Name, address = x.Address, age = x.Age, standard = x.Standard, percent = x.Percent, addedOn = x.AddedOn, status = x.Status }).ToList();
                    mStudent = targetList.ToList().FirstOrDefault();
                    ViewBag.Operation = "Update Student";
                    return View(mStudent);
                }
            }
            else
                ViewBag.Operation = "Insert Student";
            return View();
        }

        public void BindStudent(int page)
        {
            using (var context = new Entities())
            {
                int pageSize = 4;
                int pageNo = page == 0 ? 1 : page;

                PagingInfo pagingInfo = new PagingInfo();
                pagingInfo.CurrentPage = pageNo;
                pagingInfo.TotalItems = context.Student.Count();
                pagingInfo.ItemsPerPage = pageSize;
                ViewBag.Paging = pagingInfo;

                List<Models.Student> mStudentList = new List<Models.Student>();
                var result = context.sp_GetStudent(pageNo, pageSize);
                var targetList = result.Select(x => new Models.Student() { id = x.Id, name = x.Name, address = x.Address, age = x.Age, standard = x.Standard, percent = x.Percent, addedOn = x.AddedOn, status = x.Status }).ToList();
                mStudentList = targetList.ToList();
                ViewBag.StudentList = mStudentList;
            }
        }
    }

}

WebApplication_Kaido15/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication_Kaido15.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication_Kaido15/Views/CrudOperations/Index.cshtml
@model WebApplication_Kaido15.Models.Student
@using WebApplication_Kaido15.Class


@{ ViewBag.Title = "Index"; }

<h2>Index</h2>


<h4>@ViewBag.Operation</h4>
<h5>@TempData["Result"]</h5>

<div class="studentFormDiv">
    @using (Html.BeginForm())
    {
<table>
    <tr>
        <td>
            @Html.LabelFor(model => model.name)
            @Html.EditorFor(model => model.name)
            @Html.ValidationMessageFor(model => model.name)
        </td>
        <td>
            @Html.LabelFor(model => model.age)
            @Html.EditorFor(model => model.age)
            @Html.ValidationMessageFor(model => model.age)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.standard)
            @Html.EditorFor(model => model.standard)
            @Html.ValidationMessageFor(model => model.standard)
        </td>
        <td>
            @Html.LabelFor(model => model.percent)
            @Html.EditorFor(model => model.percent)
            @Html.ValidationMessageFor(model => model.percent)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.address)
            @Html.EditorFor(model => model.address)
            @Html.ValidationMessageFor(model => model.address)
        </td>
        <td>
            @Html.LabelFor(model => model.status)
            @Html.DropDownListFor(model => model.status, new List<SelectListItem> { new SelectListItem { Text = "Select", Value = "Select" }, new SelectListItem { Text = "Active", Value = "True" }, new SelectListItem { Text = "InActive", Value = "False" } })
            @Html.ValidationMessageFor(model => model.status)
        </td>
    </tr>
    <tr><td><button id="submitButton" type="submit">Submit</button></td></tr>
</table>}
</div>



@{ List<WebApplication_Kaido15.Models.Student> mStudentList = new List<WebApplication_Kaido15.Models.Student>();
    mStudentList = ViewBag.StudentList;

    if (mStudentList.Count > 0)
    {
<div class="studentDiv">
    <table>
        <thead>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Address</td>
                <td>Age</td>
                <td>Standard</td>
                <td>Percent</td>
                <td>Added On</td>
                <td>Status</td>
                <td>Edit</td>
                <td>Delete</td>
            </tr>
        </thead>
        <tbody>
            @foreach (WebApplication_Kaido15.Models.Student student in ViewBag.StudentList)
            {
<tr>
    <td>@student.id</td>
    <td>@student.name</td>
    <td>@student.address</td>
    <td>@student.age</td>
    <td>@student.standard</td>
    <td>@student.percent</td>
    <td>@student.addedOn</td>
    <td>@student.status</td>
    <td><a href="@Url.Action("Index","CrudOperations",new { id=student.id })"><img src="~/Content/Image/edit-icon.png" /></a></td>
    <td>
        @using (Html.BeginForm("Delete", "CrudOperations", new { id = student.id }))
        {
<input type="image" src="~/Content/Image/delete-icon.png" />}
    </td>
</tr>}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="10">
                    <div class="pagingDiv">
                        @Html.PageLinks((PagingInfo)ViewBag.Paging, x => Url.Action("Index", "CrudOperations", new { page = x }))
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div> } }


<style>
    #viewContent h4, #viewContent h5 {
        margin: 10px 0;
    }

    #viewContent h4 {
        color: #0184e3;
    }

    #viewContent h5, .insertLink a {
        color: #00e8ff;
    }

    #viewContent .insertLink {
        text-align: center;
    }

    #viewContent .studentFormDiv label {
        display: block;
        margin: 0;
        text-transform: capitalize;
    }

    #viewContent .studentFormDiv span {
        display: block;
        color: red;
    }

    #viewContent .studentFormDiv > form > div > div {
        padding-top: 25px;
    }

    #viewContent table {
        width: 100%;
    }

    #viewContent .studentDiv {
        padding-top: 25px;
    }

        #viewContent .studentDiv table thead {
            background-color: #0f40e0;
        }

        #viewContent .studentDiv table tbody {
            background-color: #ff6a00;
        }

    .pagingDiv {
        background: #f2f2f2;
    }

        .pagingDiv > a {
            display: inline-block;
            padding: 0px 9px;
            margin-right: 4px;
            border-radius: 3px;
            border: solid 1px #c0c0c0;
            background: #e9e9e9;
            box-shadow: inset 0px 1px 0px rgba(255,255,255, .8), 0px 1px 3px rgba(0,0,0, .1);
            font-size: .875em;
            font-weight: bold;
            text-decoration: none;
            color: #717171;
            text-shadow: 0px 1px 0px rgba(255,255,255, 1);
        }

            .pagingDiv > a:hover {
                background: #fefefe;
                background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#FEFEFE), to(#f0f0f0));
                background: -moz-linear-gradient(0% 0% 270deg,#FEFEFE, #f0f0f0);
            }

            .pagingDiv > a.active {
                border: none;
                background: #616161;
                box-shadow: inset 0px 0px 8px rgba(0,0,0, .5), 0px 1px 0px rgba(255,255,255, .8);
                color: #f0f0f0;
                text-shadow: 0px 0px 3px rgba(0,0,0, .5);
            }
</style>

WebApplication_Kaido15/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication_Kaido15/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication_Kaido15/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication_Kaido15/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - マイ ASP.NET アプリケーション</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("アプリケーション名", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ホーム", "Index", "Home")</li>
                    <li>@Html.ActionLink("詳細", "About", "Home")</li>
                    <li>@Html.ActionLink("問い合わせ", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - マイ ASP.NET アプリケーション</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>